# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

#env
ENV NODE_ENV=production

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the app
CMD ["node", "publict/index.js"]