name: CI/CD Pipeline Natours

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./minhvo99-natours-server
        run: npm ci

      - name: Run Lint
        working-directory: ./minhvo99-natours-server
        run: npm run lint

      - name: Build TypeScript
        working-directory: ./minhvo99-natours-server
        run: npm run build

      - name: Build Docker Image
        working-directory: ./minhvo99-natours-server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/minhvo99-natours-server:latest .
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/minhvo99-natours-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment-directory
            docker-compose pull
            docker-compose up -d --build
